### ISSUE TITLE
Add to donators group only if the exact price is donated

### ISSUE THREAD

**Issue by PepinCZ** [Skouat/ext_paypal_donation#25]
Hello,
thank you for awesome extension!
However, I making adjustments to it, because I will use it as extension to buy with PayPal.
But I rant into a big problem: when the client don't pay the minimum price that is in menu, he still will be added to donators group.

How to do that?

**Comment by Skouat** [comment]
Hi,

Sorry, I had not seen this ticket.
I'm not sure to understand your issue.
In which case, the client can't pay the minimum price if you set a minimum value through the ACP?

Be aware that this extension is dedicated only for donation.
Use this ext for buy system requires some adjustments.
