### ISSUE TITLE
Invalid response status:[args]

### ISSUE THREAD

**Issue by efinst0rm** [Skouat/ext_paypal_donation#36]
Hey,

I have your extension installed and the donation part works. But the donors table never updates and the only error I see is " Invalid response status:[args]" and then donors info.

Thanks.

**Comment by Skouat** [comment]
Which version did you install? The [1.0.2](https://github.com/Skouat/ext_paypal_donation/releases/tag/1.0.2)?

When and where did you get this error? On screen? In the error log file?
Did you use the Sandbox Mode or not?

**Comment by efinst0rm** [comment]
Hey, 

I only see that error I'm donation error log and, I believe I haven't tried the sandbox mode. I am using the newest version from your github. But the  error was there before I updated.

**Comment by Skouat** [comment]
Please, could you...
* Enable the error log transactions
* Delete the file `store/ppde_transactions.log`
* Make a donation by using the Sandbox mode.  
Read this [user guide](https://github.com/Skouat/ext_paypal_donation/wiki/Testing-accounts-information) to use it.
* Copy/paste the content of the `ppde_transactions.log` on https://gist.github.com/

**Comment by efinst0rm** [comment]
Hey Skouat,
https://gist.github.com/efinst0rm/95768bd78dda6f1f54220057ca63be9d

**Comment by Skouat** [comment]
All seems to works as expected.
* PayPal IPN use the [cURL](https://gist.github.com/efinst0rm/95768bd78dda6f1f54220057ca63be9d#file-ppde_transactions-log-L3) function.
* The Sandbox transaction returns the response [200](https://gist.github.com/efinst0rm/95768bd78dda6f1f54220057ca63be9d#file-ppde_transactions-log-L26) and the status [VERIFIED](https://gist.github.com/efinst0rm/95768bd78dda6f1f54220057ca63be9d#file-ppde_transactions-log-L24).

Normally, you will see one transaction in the "transactions log" module.

Please, could you...
* Disable Sandbox mode,
* Delete the file `store/ppde_transactions.log`
* Make a real donation (or wait a real donation).
* Edit the `ppde_transactions.log` by changing all personal data stored in [this part](https://gist.github.com/efinst0rm/95768bd78dda6f1f54220057ca63be9d#file-ppde_transactions-log-L28-L63)
* Create a gist of the `ppde_transactions.log`.

**Comment by efinst0rm** [comment]
Hey,

https://gist.github.com/efinst0rm/bfbf7d56de251eac2a638a48266c74e3

**Comment by Skouat** [comment]
Please could you check if PayPal logs IPN transactions by clicking on the following link
https://www.paypal.com/fr/cgi-bin/webscr?cmd=_display-ipns-history

**Comment by efinst0rm** [comment]
Thank you, Seems that paypal doesn't allow you to use a personal account to use IPN logs only business. Thanks for your help issue is on my end.

**Comment by Skouat** [comment]
You can enable IPN with a personnal account.
* Connect on your PayPal account and go to `Seller preferences` from the `Home` page
* Look for `Instant payment notifications` then click `update`
* Click the button `Choose IPN Settings`
* Enter your board URL in `Notification URL` and check `Receive IPN messages` button
* Save changes

But it's recommanded to migrate to a business account (it's free of charge).

**Comment by efinst0rm** [comment]
When I tried to click the link before or find Seller Preferences. I get this.
 
![taczd9t9hn4v5gb36vnr](https://cloud.githubusercontent.com/assets/7751074/18234197/dc471884-72c1-11e6-95ea-abcc8fb955ea.png)

**Comment by Skouat** [comment]
I remember one day I upgraded my account from "Personal" to "Premium".
https://www.paypal.com/cgi-bin/webscr?cmd=p/pop/choosing_account_type_signup-outside
