### ISSUE TITLE
general settings error

### ISSUE THREAD

**Issue by rec0d** [Skouat/ext_paypal_donation#39]
when go to general settings giving this error

Catchable fatal error: Object of class phpbb\template\twig\twig could not be converted to string in C:\xampp\htdocs\forum\phpbb\extension\metadata_manager.php on line 131

useing 3.2 stable.

useing this one version of plugin:

PayPal Donation
Clean Name: skouat/ppde
Description:
An extension which allows you to add a PayPal donation page on your phpBB board
Version: 2.0.0-dev
Homepage: http://skouat.github.io/ext_paypal_donation
Licence: GPL-2.0

**Comment by Skouat** [comment]
I will working on it this weekend
