### ISSUE TITLE
match by email

### ISSUE THREAD

**Issue by bshow80** [Skouat/ext_paypal_donation#41]
Can you add a feature to look at the member's email address in phpBB and compare it to paypal email? It would be nice to have since a lot of my users donate each month and do not always use the button on the site.

**Comment by Skouat** [comment]
Source request: https://www.phpbb.com/customise/db/extension/paypal_donation_extension/support/topic/172206?p=536356#p536356

**Comment by Skouat** [comment]
I need to check the code, because from what I remember this check already exists

**Comment by Skouat** [comment]
As suspected, the email check is already implemented.
cf. [Line 733 - 744](https://github.com/Skouat/ext_paypal_donation/blob/develop-3.2.x/controller/ipn_listener.php#L733-L744)

Based on your use of PayPal with this extension, you have found a bug :yum: 

The commit https://github.com/Skouat/ext_paypal_donation/commit/9cb3c70eff05748f4487f5cf9235c473edf9143b Fix this issue.

Please can you try and let me know?

Thx!
