### ISSUE TITLE
 Object of class phpbb\template\twig\twig could not be converted to string

### ISSUE THREAD

**Issue by Owned67** [Skouat/ext_paypal_donation#42]
( ! ) Catchable fatal error: Object of class phpbb\template\twig\twig could not be converted to string in C:\UwAmp\www\forum\phpbb\extension\metadata_manager.php on line 131
Call Stack
#	Time	Memory	Function	Location
1	0.0055	147448	{main}( )	...\index.php:0
2	0.6686	10636104	p_master->load_active( )	...\index.php:82
3	0.7516	10668400	skouat\ppde\acp\ppde_module->main( )	...\functions_module.php:676
4	0.7556	10845856	skouat\ppde\controller\admin_overview_controller->display_overview( )	...\ppde_module.php:58
5	0.7556	10845904	skouat\ppde\controller\main_controller->first_start( )	...\admin_overview_controller.php:81
6	0.7671	10831072	skouat\ppde\controller\main_controller->set_remote_detected( )	...\main_controller.php:838
7	0.7671	10831136	skouat\ppde\controller\main_controller->check_curl( )	...\main_controller.php:901
8	0.7671	10831192	skouat\ppde\controller\main_controller->get_ext_meta( )	...\main_controller.php:860
9	0.7671	10831304	skouat\ppde\controller\main_controller->load_metadata( )	...\main_controller.php:915
10	0.7676	10876592	phpbb\extension\metadata_manager->get_metadata( )	...\main_controller.php:937
11	0.7676	10876664	phpbb\extension\metadata_manager->set_metadata_file( )	...\metadata_manager.php:84

phpbb 3.2.0
php 5.6.18
Version 1.0.2 du mod

L'erreur se produit quand je vais dans le module (n'importe ou: vue d'ensemble et parametres uniquement, les autres pages s'affiches)

**Comment by Skouat** [comment]
La version 1.0.2 n'est pas compatible avec phpBB 3.2.0

Il faut à minima partir sur la version 2.0.0 de l'extension.

**Comment by Owned67** [comment]
Bah il y a une erreur sur le topic alors car j'ai beau téléchargé cette version: http://forums.phpbb-fr.com/extensions-developpement-en-cours/sujet209462.html j'ai toujours la 1.0.2

**Comment by Skouat** [comment]
L'extension a été désactivée puis réactivée ?
Car les liens présents dans le sujet mentionné amènent bien à la version 2.0.0-dev

**Comment by Owned67** [comment]
oui ainsi que suppression du cache.

1.0.2:
L’extension a été désactivée.

Êtes-vous sûr de vouloir activer l’extension « PayPal Donation » ?
L’extension a été activée.
1.0.2

**Comment by Owned67** [comment]
et bah après plusieurs tentatives, c'est bon, j'ai la 2.0.0
