### ISSUE TITLE
Currency Formatting for Goal Total

### ISSUE THREAD

**Issue by surfshopcart** [Skouat/ext_paypal_donation#43]
Unless I've missed it, I don't see a way to add a thousand separators to the goal total, e.g. to display $10000 as $10,000.  If you add a comma in the Donation Goal text box, everything after the comma is truncated.  Is there a way to format the goal total on the forum pages?

**Comment by Skouat** [comment]
Hi,

Currently, the extension does not support thousands separators.

**Comment by surfshopcart** [comment]
Can you tell me which file that figure is generated?  Perhaps I could add it myself.

Thanks,
Frank

**Comment by Skouat** [comment]
This is an enhancement. The only clue I can provide is the following : http://php.net/manual/fr/function.money-format.php

Currently, values are formatted with the "float" type. I must include the money format in the code.

**Comment by Skouat** [comment]
Hi,

2 years later… this feature is implemented in the future release 2.2.0.
You can test it by downloading [PPDE 2.0.0-dev](https://github.com/Skouat/ext_paypal_donation/tree/develop-3.2.x-2.2). Be aware, this is a development version.

**Comment by Skouat** [comment]
Feature fully added in release [3.0.1](https://github.com/Skouat/ext_paypal_donation/releases/tag/3.0.1)
