### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by flax50** [Skouat/ext_paypal_donation#47]
On the Extensions tab, I can access "Donation Pages", Currency management", and "Transaction log" with no issue. When I try to access "Overview", General Settings", and "PayPal IPN Features", I get a 500 error. There is nothing in the server error log or the phpBB Error Log.

phpBB: v3.2.1
php: v5.6.30
ppde: v2.0.0-dev

**Comment by Dark6031** [comment]
Same error for me and same setup as flax50. I had same error on previous version also ppde v1.0.3 though the update would fix the issue but it didn't.

phpBB v3.2.1
php v5.6.30
ppde v2.0.0-dev

**Comment by flax50** [comment]
Also, I have toggled both the Administrators Group and my user account permissions off and on for the ppde extension. I'm still getting the 500 error.

**Comment by Skouat** [comment]
Hi Guys,

Error spotted. Something has changed in phpBB 3.2.1
Thanks for the report

**Comment by flax50** [comment]
Thanks for the quick work! 

Unfortunately it doesn't seem to have fixed my problem. Just to make certain I attempted the update correctly, I tried it two ways:

Disable ppde ext, delete data, purge cache, delete files in the ppde folder, upload "ext_paypal_donation-develop-3.2.x-twig_conversion" files, purge cache, enable ppde, "Yes" for admin permission for my account to configure ppde

Disable ppde ext, delete data, purge cache, delete files in the ppde folder, upload "ext_paypal_donation-develop-3.2.x-donors_module" files, upload "ext_paypal_donation-develop-3.2.x-twig_conversion" files, purge cache, enable ppde, "Yes" for admin permission for my account to configure ppde

I did this with all other extensions disabled. When I click on the EXTENSIONS tab, I get a 500 error. 

If I enable another extension, I can view the EXTENSIONS tab, but clicking on Overview, etc. results in a 500 error.

**Comment by Skouat** [comment]
This is normal. no fix was applied. ;)
I've only spotted the error.
I thought I could fix this quickly, but it completely affects the overview module.

**Comment by Dark6031** [comment]
Do we only have to replace the main_controller file with the new one ? 

If I do so my forum redirects to your github site making the forum inaccessible, 

Merci

**Comment by Skouat** [comment]
Yes, you can only replace the changed file.

> If I do so my forum redirects to your github site making the forum inaccessible,

O_o

There is no reference to Github on PPDE files.
Another way to update is to read instructions described on the Extension Panel on your board ;)
* Disable extension
* Replace files
* Enable extension

;)

**Comment by Dark6031** [comment]
Hi Mario,

Thanks for replying but it does redirect I know how to update an extension also.

Look here: http://imgur.com/hgl8wyU

If I put the backup main_controller.php back in the forum loads just fine with the new files it does redirect to the github. Something is wrong with the new file for sure.

**Comment by Skouat** [comment]
It doesn't make sense.
It's like you have copied the html code and not the RAW file

Please, download the full package https://github.com/Skouat/ext_paypal_donation/archive/develop-3.2.x.zip

**Comment by Dark6031** [comment]
Damnit you are right !

My bad not used to play with Github, I checked the file and I was indeed grabbing the file with the github html code. With the full package everything works well. Keep up the good work !

Merci beaucoup pour ton temps et désolé pour mon erreur :(
