### ISSUE TITLE
Sandbox Account Not Working

### ISSUE THREAD

**Issue by flax50** [Skouat/ext_paypal_donation#51]
The Wiki page shows the following info for sandbox testing with USD:

email: buyer-usd@ppde-testing.tld
password: buyer-usd

PayPal reports the following:

"Some of your info isn't correct. Please try again."

**Comment by Skouat** [comment]
Hi,

I've tested the account and credentials work as expected.

Are you sure that the IPN Features are enabled?

**Comment by flax50** [comment]
It is working now. Perhaps it was a temporary PP issue.

Thanks!

**Comment by Skouat** [comment]
Good news.
