### ISSUE TITLE
"Donations" Link Not Showing for Users

### ISSUE THREAD

**Issue by flax50** [Skouat/ext_paypal_donation#52]
The "Donations" link appears correctly for members of the Administrators group, but not for users.

I created a test user account and logged in. I did not see the "Donations" link. After I added that account to the Administrators group, the link appeared. When I removed the account from the Administrators group, the link disappeared.

Also, is there a way to make the Donations" link appear in a different color so that it stands out?

**Comment by Skouat** [comment]
Hi,

> The "Donations" link appears correctly for members of the Administrators group, but not for users.

By default, the anonymous account have no access to the donation link.
You must set the appropriate permissions for the "Anonymous" account or the "Guests" group

> Also, is there a way to make the Donations" link appear in a different color so that it stands out?

Link use the [PayPal font-awesome](http://fontawesome.io/icon/paypal/) icon. So you can ajust the color if you want, by editing the file [overall_header_navigation_prepend.html](https://github.com/Skouat/ext_paypal_donation/blob/develop-3.2.x/styles/prosilver/template/event/overall_header_navigation_prepend.html)

**Comment by flax50** [comment]
My bad—I missed setting the ppde permissions on registered users.

Thanks for the info on the font color. An easy fix!
