### ISSUE TITLE
Donor List: total donation of $1,000 show as $1

### ISSUE THREAD

**Issue by DrunkMunki** [Skouat/ext_paypal_donation#55]
I have had someone over a long period of time donate a total of $1,000 ...
when i sort by donation amount, it shows at the top of the list, but shows $1

![donors](https://user-images.githubusercontent.com/865746/29995464-11c24072-902d-11e7-9170-340a7e29f284.JPG)

i checked the html source code and it shows $1, so its not a theme issue.

**Comment by Skouat** [comment]
Hi,

Which version of PPDE do you use?

Please can you run the following SQL query?

```
SELECT SUM(txn.mc_gross) AS amount, u.username
FROM (phpbb_ppde_txn_log txn)
LEFT JOIN phpbb_users u ON (u.user_id = txn.user_id)
WHERE u.user_id = <you_user_id>
AND txn.payment_status = 'Completed'
AND txn.test_ipn = 0
GROUP BY txn.user_id
ORDER BY txn.payment_date DESC;
```
Replace the "table_prefix" `phpbb_` with yours
Replace `<you_user_id>` with the ID of the user affected by this issue.

**Comment by DrunkMunki** [comment]
Current PPDE version is 1.0.3

Ok i have done what you requested which shows the below results
![sql_query](https://user-images.githubusercontent.com/865746/29999047-a430bc7c-907d-11e7-95e6-e150f7921893.JPG)

**Comment by Skouat** [comment]
Please, can you apply the quick fix mentionned above?

**Comment by DrunkMunki** [comment]
thanks, confirmed the fix worked :)

**Comment by Skouat** [comment]
Hi,

Follow [this link](https://github.com/Skouat/ext_paypal_donation/compare/077ae6a...2aa5ca8) for a better fix.
