### ISSUE TITLE
TLS 1.2 sous la version 3.0.0

### ISSUE THREAD

**Issue by association-amis** [Skouat/ext_paypal_donation#89]
**FR /** Bonjour SKOUAT 

Voulant tester la version pour phpbb 3.3.1 l’extension en développement "coince" dans la détection TLS 1.2  pour l'activation de Paypal IPN.
Nous sommes en 3.3.1 php 7.3.22  En espérant que cela puisse t'aider  
Bonne journée 

**EN/** Hello SKOUAT

Wanting to test the version for phpbb 3.3.1 the extension in development "gets stuck" in the TLS 1.2 detection for the activation of Paypal IPN.
We are on 3.3.1 php 7.3.22 Hope this can help you
Have a good day

**Comment by Skouat** [comment]
Hello,

Le forum est bien accessible en https ?

**Comment by association-amis** [comment]
Hello 
Oui le forum est bien accessible en https avec un certificat let's ENCRYPT 
Voici les informations techniques qui apparaissent sur l'onglet sécurité du certificat 
Connexion chiffrée (clés TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 128 bits, TLS 1.2)

https://www.myasthenie.com  

Bonne journée

**Comment by Skouat** [comment]
Est-ce que la version de SSL est bien détectée par PPDE ?

Accédez en SSH à votre serveur et executez la commande suivante
```
wget https://www.howsmyssl.com/a/check
```
Cela devrait retourner un message comme celui-ci

> Resolving www.howsmyssl.com (www.howsmyssl.com)... 34.71.45.200                                                                                                                     
> Connecting to www.howsmyssl.com (www.howsmyssl.com)|34.71.45.200|:443... connected.                                                                                                 
> HTTP request sent, awaiting response... 200 OK                                                                                                                                      
> Length: 1325 (1.3K) [application/json]                                                                                                                                              
> Saving to: ‘check’                                                                                                                                                                  
>                                                                                                                                                                                     
> check                                        100%
[==============================================================================================>]   1.29K  --.-KB/s    in 0s       
>                                                                                                                                                                                     
> 2020-10-31 15:01:29 (24.9 MB/s) - ‘check’ saved [1325/1325]

Si vous voyez bien ce message, alors executez la commande
```
cat check
```
puis copiez le contenu du fichier `check` ici.
