### ISSUE TITLE
Amount received: 0

### ISSUE THREAD

**Issue by wads24** [Skouat/ext_paypal_donation#92]
Why is the amount received in emails now showing 0.00?
Example:
Amount donated: $26.07
Amount received: 0

I'm also getting ipn on all payments received on my PayPal account that are not related to forum donations added as domain from anonymous but guest donations is disabled

**Comment by Skouat** [comment]
Hi @wads24 

What is your PPDE version ?

> Why is the amount received in emails now showing 0.00?
Example:
Amount donated: $26.07
Amount received: 0

Does the defaulft currency set on PPDE is $ or another currency?

> I'm also getting ipn on all payments received on my PayPal account that are not related to forum donations added as domain from anonymous but guest donations is disabled

For convenience, please open a new issue for this part of your message.

**Comment by Skouat** [comment]
Additionnal question: Have you set the option "locale settings"?

**Comment by wads24** [comment]
> Hi @wads24
> 
> What is your PPDE version ?
> 
> > Why is the amount received in emails now showing 0.00?
> > Example:
> > Amount donated: $26.07
> > Amount received: 0
> 
> Does the defaulft currency set on PPDE is $ or another currency?
> 
> > I'm also getting ipn on all payments received on my PayPal account that are not related to forum donations added as domain from anonymous but guest donations is disabled
> 
> For convenience, please open a new issue for this part of your message.


Default is $
StatisticPayPal Donation Extension version:
3.0.1 [ More information… ]
StatisticInstall date of PayPal Donation Extension:
November 19th, 2018, 7:23 pm
StatisticcURL version:
7.74.0
StatisticSSL version:
OpenSSL/1.1.1i
StatisticTLS 1.2:
Detected
StatisticPHP Intl version:
7.3.26

> Additionnal question: Have you set the option "locale settings"? 

No, I don't believe so... I don't see this option.
